name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-16.04
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Clone clsocket
      uses: actions/checkout@v1
    - name: Configure
      run:
        cmake -S . -B build -D CLSOCKET_EXAMPLES:BOOL=ON
    - name: Build
      run:
        cmake --build build
